application: soloiago
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# image files
- url: /images/(.*\..*)
  static_files: static/images/\1
  upload: static/images/(.*\..*)

# css files
- url: /styles/(.*\..*)
  static_files: static/styles/\1
  upload: static/styles/(.*\..*)

# javascript files
- url: /javascript/(.*\..*)
  static_files: static/javascript/\1
  upload: static/javascript/(.*\..*)

- url: /.*
  script: soloiago.app


libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
